name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CD:
    runs-on: [self-hosted, docker, analyzers-build]
    container:
      image: node:14
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Create package
        run: npm run createPackage
      - name: Publish
        run: | 
          has_skip_ci=$(node node_modules/@analyzers/publish-and-tag/printFlagCommitMessageHasSkipCI --sha=$GITHUB_SHA --repo=$GITHUB_REPOSITORY)
          echo $has_skip_ci          
          if [ $has_skip_ci -eq 1 ]
          then
            echo "skip-ci token present in commit message, skipping CI workflow"
            exit 0
          fi
          echo ${{secrets.ARTIFACTORY_NPM_TOKEN}} >> .npmrc
          node node_modules/@analyzers/publish-and-tag/index --sha=$GITHUB_SHA --repo=$GITHUB_REPOSITORY --githubKey=${{secrets.INNERSOURCE_RW_TOKEN}}
